version: '3.8'
services:
  db:
    image: alpine:latest
    volumes:
      - ./database:/data/db
    command: sh -c "apk add --no-cache sqlite && tail -f /dev/null"
    container_name: sqlite_containter
